### ISSUE TITLE
ἱερόν or ἱερός

### ISSUE THREAD

**Issue by jtauber** [morphgnt/sblgnt#36]
From #32 

ἱερόν is used as a lemma 29 times and ἱερός is used as a lemma 44 times. They are always tagged as adjectives so aren't really being treated as cross-overs except in lemma.

**Comment by emg** [comment]
I(ERO/N should probably be treated as a cross-over adjective that has become a noun, IMHO.

Friberg & Friberg have a special tag-class for cross-over adjectives.  Is that something to consider here?

**Comment by jtauber** [comment]
My only hesitation is I really want to just provide a formal morphological analysis here and leave the questions of syntactic function to another "layer". I can avoid the part-of-speech question because I'm just going to start using a scheme based on  http://jktauber.com/2015/11/05/morphological-parts-speech-greek/ and leave the full part-of-speech distinction to the "syntax" layer, but that doesn't solve the lemmatization choice. Even if adjectives and nouns are conflated at the morphology tagging level, the lemma forces a choice.

**Comment by emg** [comment]
In that case, why not leave it as a neuter adjective rather than a neuter noun?

The issue with MAKRA/N and U(/STERON is a different one, namely one of syntagmatic relations that indicate that both are adverbs rather than neuter adjectives.  For I(ERO/N, the syntax (e.g., preceding article) would seem to indicate that these are morphologically adjectives that are being used as nouns.

So, for I(ERO/N, and given that you want to provide a formal analysis, it is probably good to go with ASN and I(ERO/S.

**Comment by jtauber** [comment]
Yep, I'm inclined to go with ASN with ἱερός for lemma.
