### ISSUE TITLE
ἄγε as lemma

### ISSUE THREAD

**Issue by jtauber** [morphgnt/sblgnt#39]
From #32 

In James

    80-Jas-morphgnt.txt:200413 V- 2PAD-S-- Ἄγε Ἄγε ἄγε ἄγε
    80-Jas-morphgnt.txt:200501 V- 2PAD-S-- Ἄγε Ἄγε ἄγε ἄγε

If ἄγε is lemmatized as ἄγε it shouldn't be tagged as an imperative verb. So two choice are: (1) tag differently or (2) change lemma to ἄγω

Depending on how we want to treat words like this.

**Comment by emg** [comment]
I would go with (2), since morphologically, that is what it appears to be.  The interjection-analysis (which I assume is what you mean by (1)) would be, IMHO, a case of superimposing English pos-categories onto Greek. Thayer does list A)/GE separately, and says that it is "properly, the imperative of A)/GW".  However, syntactically, the contexts assume a fuller clause than just an interjection with an adverb of time: There is a full-orbed subject for each of the A)/GE-s, in nominative plural.  Thayer notes that A)/GE has been used thus since classical times, regardless of the number of the subject.  So, (2) seems the better way to go.

**Comment by jtauber** [comment]
Liddell lists ἄγε separately, too, although gives ἄγετε as plural, describe the lexical item as " imper. of ἄγω, used as Adv."

But yeah, this is a case of the tagging and lemmatization making inconsistent choices. Consistency is more important than which we go with but I'm happy to do with (2).

Question is whether we do that for ἰδοῦ τοο?

**Comment by emg** [comment]
I)DOU= is a little different from A)/GE.  Syntactically, I)DOU= often occurs as a left dislocation outside the main clause, without any verbal satellites, indicating it is probably thought of as an interjection.  A)/GE, on the other hand, comes with verbal satellites such as an adverb of time (NU=N) and a subject.  So for syntactic reasons, I'd say I)DOU= is most often to be treated as an interjection rather than an inflection of a verb.
