### ISSUE TITLE
010205 && 010704

### ISSUE THREAD

**Issue by verite** [morphgnt/sblgnt#59]
010205 V- 3AAI-P-- εἶπαν εἶπαν εἶπαν λέγω
ἔπω

010704 V- 2FAI-S-- ἐρεῖς ἐρεῖς ἐρεῖς λέγω
ἐρέω

**Comment by jtauber** [comment]
Not sure what you are suggesting here. Changing the way the suppletive forms are handled? I probably won't change that here as they are traditionally lemmatized as λέγω but in my broader morphological lexicon I will model them in such a way that the stem is more explicit.

**Comment by verite** [comment]
Respectfully, but it's a false lemmatization.

**Comment by verite** [comment]
Do you have a computer program that gives the right lemma ?
With here ἔπω for εἶπαν and ἐρέω for ἐρεῖς

**Comment by jtauber** [comment]
BDAG, LSJ, and BrillDAG all give these as suppletive forms of λέγω. The BDAG entry for ἐρῶ just redirects to εἶπον, the entry for which begins "used as 2 aor. of λέγω". BDAG doesn't even have entries for ἔπω or ἐρέω. Some lemmatizations might give εἶπον as the lemma for both, especially based on BDAG. I believe Logos does this. See also BDF which says of λέγειν "in the NT it is defective with only pres. and impf. appearing; fut. ἐρῶ, aor. εἶπον and εἶπα".

**Comment by verite** [comment]
Perseus  εἶπαν : εἶπον
http://www.perseus.tufts.edu/hopper/morph?l=%CE%B5%E1%BC%B6%CF%80%CE%B1%CE%BD

Perseus ἐρεῖς : ἐρέω
http://www.perseus.tufts.edu/hopper/morph?l=%E1%BC%90%CF%81%CE%B5%E1%BF%96%CF%82

**Comment by jtauber** [comment]
One reason Morpheus gives ἐρέω for ἐρεῖς is that it is covering a broader time period and dialects (and because it is lemmatizing against LSJ which has a separate entry for ἐρέω, although it just directs one to ἐρῶ which is the future of εἴρω. But as Middle Liddell says under ἐρῶ: "the place of the pres. εἴρω (rare even in Epic and never in Attic) is supplied by φημί, λέγω or ἀγορεύω; and εἶπον serves as the aor."

As well as the lexicons, the grammars will group the stems λεγ- εἰπ- ἐρ- under λέγω. (see, for example 15.34 in the Cambridge Grammar of Classical Greek)

**Comment by verite** [comment]
If it's three words with different precise definitions, it's a loss.

**Comment by jtauber** [comment]
They are not generally considered three words with different definitions, though, especially not in the Koine. They are suppletive forms of the same word (see the reference in the Cambridge Grammar of Classical Greek above). Because they have different stems and different origins, they will be treated slightly differently in my morphological lexicon but for the purposes of a simple lemmatization, using λέγω for all of them is a common approach, especially if the objective is to map to an appropriate lexicon. εἶπον would possibly be okay as its own lemma. That's not wrong, just a different approach and there is no principled reason for me to change to it at this time. A move to an approach like I discussed in my SBL 2017 talk rather than using an actual form would help support that. But I think something like ἔπω would just be wrong. It's not in BDAG and LSJ suggests it's made up.

This all just highlights the problem with using a single form as the link to lexical information which is why I plan to ultimately abandon it.
